### ISSUE TITLE
Request for official support for Python >3.8

### ISSUE THREAD

**Issue by jensens** [zopefoundation/zope.i18nmessageid#31]
It would be great to tests running and wheels released for all recent Python versions such as 3.9+3.10.

**Comment by icemac** [comment]
https://github.com/zopefoundation/zope.i18nmessageid/pull/27 has to be completed to resolve this issue.

**Comment by frispete** [comment]
Now, that this is addressed with the new 5.1.0 release, do you plan to release a source tarball as well?

**Comment by icemac** [comment]
> Now, that this is addressed with the new 5.1.0 release, do you plan to release a source tarball as well?

See #33 where that issue should be fixed.
