### ISSUE TITLE
six seems to be unused

### ISSUE THREAD

**Issue by mgorny** [zopefoundation/zope.i18nmessageid#37]
### What I did:

`grep -R six` ;-)

### What I expect to happen:

Ideally, no dependency on `six`, or at least code using `six`.

### What actually happened:

It seems that `six` is a declared as a dependency but it's not used anywhere in the code.

### What version of Python and Zope/Addons I am using:

Gentoo Linux, Python 3.11.2, zope-i18nmessageid 6.0.0

**Comment by icemac** [comment]
This ist going to be fixed in #36.

**Comment by icemac** [comment]
Fix released in https://pypi.org/project/zope.i18nmessageid/6.0.1/

**Comment by mgorny** [comment]
Thank you!
